server:
  port: 8081
  servlet:
    contextPath: /
spring:
  datasource-gc:
    url: jdbc:postgresql://localhost:5432/grade_curricular
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  datasource-oauth:
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
host:
  full:
    dns:
      auth:
        link: http://localhost:8081/oauth/token
